version: 2.1
orbs:
  allure: ayte/allure@0.1.3
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - allure/install
      - run:
          name: Test
          command: mvn clean test
      - store_test_results:
          path: target/surefire-reports
      - run:
          name: clean Allure report generation path
          command: rm -rf allure-report
      - run:
          name: Generate Allure Report
          when: always
          command: allure generate target/allure-results
      - store_artifacts:
          path: allure-report
workflows:
  sample:
    jobs:
      - build-and-test